[tool.isort]
profile = "black"
src_paths = ["inboard", "tests"]

[tool.poetry]
name = "inboard"
version = "0.1.0"
description = "Docker images to power your Python APIs and help you ship faster."
authors = ["Brendon Smith <br3ndonland@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/br3ndonland/inboard"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.3"
gunicorn = "^20"
uvicorn = "^0.11.8"
fastapi = {version = "^0.60.1", optional = true}
starlette = {version = "^0.13.6", optional = true}

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
flake8 = "*"
isort = "^5.2.2"
mypy = "*"
pre-commit = "^2.6"
pytest = "^5.4"
pytest-mock = "^3"

[tool.poetry.extras]
fastapi = ["fastapi"]
starlette = ["starlette"]

[tool.pytest.ini_options]
# Pytest v6 will use [pyproject.toml](https://docs.pytest.org/en/latest/customize.html)
addopts = "-q"
minversion = "6.0"
testpaths = ["tests"]

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
