name: builds

on:
  push:
    branches: [develop, master]
    tags:
      - "[0-9v]+.[0-9]+.[0-9a-z]+"
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set PY environment variable for caching
        run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
      - name: Set up Poetry cache for Python dependencies
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ env.PY }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-${{ env.PY }}-
      - name: Set up pre-commit cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ env.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-pre-commit-${{ env.PY }}-
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install --no-interaction -E fastapi
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Run unit tests
        run: pytest
      - name: Build Python package and publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          poetry config pypi-token.inboard ${{ secrets.PYPI_TOKEN }}
          poetry publish --build inboard
  docker:
    runs-on: ubuntu-latest
    needs: [python]
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker registry
        run: docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ github.token }}
      - name: Build Docker images
        run: |
          docker build . --rm --target base -t docker.pkg.github.com/br3ndonland/inboard/base:latest --cache-from python:3.8
          docker build . --rm --target fastapi -t docker.pkg.github.com/br3ndonland/inboard/fastapi:latest
          docker build . --rm --target starlette -t docker.pkg.github.com/br3ndonland/inboard/starlette:latest
      - name: Push Docker images to registry
        run: |
          docker push docker.pkg.github.com/br3ndonland/inboard/base:latest
          docker push docker.pkg.github.com/br3ndonland/inboard/fastapi:latest
          docker push docker.pkg.github.com/br3ndonland/inboard/starlette:latest
      - name: Add Git tag to Docker images if workflow was triggered by pushing a tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          GIT_TAG=$(echo ${{ github.ref }} | cut -d / -f 3)
          docker tag docker.pkg.github.com/br3ndonland/inboard/base docker.pkg.github.com/br3ndonland/inboard/base:"$GIT_TAG"
          docker tag docker.pkg.github.com/br3ndonland/inboard/fastapi docker.pkg.github.com/br3ndonland/inboard/fastapi:"$GIT_TAG"
          docker tag docker.pkg.github.com/br3ndonland/inboard/starlette docker.pkg.github.com/br3ndonland/inboard/starlette:"$GIT_TAG"
          docker push docker.pkg.github.com/br3ndonland/inboard/base:"$GIT_TAG"
          docker push docker.pkg.github.com/br3ndonland/inboard/fastapi:"$GIT_TAG"
          docker push docker.pkg.github.com/br3ndonland/inboard/starlette:"$GIT_TAG"
